allow-other: true

azstorage:
  type: block
  account-name: msranlpintern
  account-key: GmB6riG7iRFIVQO/z/R+3nUpGaak+uLSY0RW8wQMpNOeWzC9vUvSb/2qwibXVM9+9GajoorHPNFg+AStTJ5LEQ==
  mode: key
  container: yuxian
